### ISSUE TITLE
Incorrect CMAC signing & verification in 7.0

### ISSUE THREAD

**Issue by Igetin** [Thealexbarney/LibHac#102]
When verifying the CMAC signature of a save, hactoolnet 7.0 will report `FAIL` for an unmodified save file’s signature:

```
CMAC Signature (FAIL):   7F404B234AD960F0E21A95C339DBFAA2
Title ID:                01008db008c2c000
```

When verifying the same file’s signature with hactoolnet 6.0, it outputs `GOOD`. SciresM’s hactool also reports the signature as `GOOD`.

The file also gets incorrectly re-signed when using the `--replacefile` option, it outputs:

```
CMAC Signature (GOOD):   AE02AAC2310A738817D82AEE0E8B204F
```

Verifying the edited save with hactoolnet 6.0 and hactool will result in `FAIL`.

If I replace the original save file on Switch with this file and try to start the game, it gives me this message:

> Corrupted data has been detected. Please run a check for corrupt data.

Pressing “Check” will result in a screen that prompts to delete the save data.

When editing and re-signing the save file with hactoolnet 6.0, it works properly on the Switch.

---

I’m using the Linux release of hactoolnet 7.0, but I also tried it on Windows and replicated the same problem. People in [this thread](https://gbatemp.net/threads/edit-ofw-clean-switch-save-data-from-nand-backup-restoring-via-fusee-gelee-payloads.541081/page-5#post-8876076) seem to be having the same issue.

**Comment by Thealexbarney** [comment]
Can you verify if the `save_mac_key` being used between the two versions is the same or different?

With each version run `hactoolnet.exe -t keygen --outdir keys`, open the output console.keys file, and check the `save_mac_key` used by each version.

**Comment by Thealexbarney** [comment]
@Igetin Is this still an issue?

**Comment by Igetin** [comment]
> Can you verify if the `save_mac_key` being used between the two versions is the same or different?

I can check this probably this weekend.

> @Igetin Is this still an issue?

Not sure why it wouldn’t be, unless you released a new version with a fix (doesn’t seem like it). I’ve been using only version 6.0, which does not have the problem.

**Comment by dedwardsdale** [comment]
I'm also facing this issue, downgrading to 5.0_native works correctly.

**Comment by Thealexbarney** [comment]
@dedwardsdale Can you run the commands from one of my previous comments and check if both versions are using the same keys?

**Comment by dedwardsdale** [comment]
@Thealexbarney keys returned for `save_mac_key` are not the same:  

`v0.7.0 - hactoolnet.exe - 2A2CBCE8E30551E2C06F2A5E82445A0F`
 
`v0.6.0 - hactoolnet.exe - 6F0728EC566720F043B4D7F10DB3D303`
`v0.6.0 - hactoolnet_native.exe - 6F0728EC566720F043B4D7F10DB3D303`

`v0.5.1 - hactoolnet.exe - 6F0728EC566720F043B4D7F10DB3D303`
`v0.5.1 - hactoolnet_native.exe - 6F0728EC566720F043B4D7F10DB3D303`

The same `prod.keys` file was used across all.

**Comment by Thealexbarney** [comment]
Thanks, that confirms my suspicion. I wasn't able to reproduce the issue on my end, so I couldn't check myself. 

Would you be willing to send your console keys, @dedwardsdale? You can email me at the email my git commits use, or we could message on something like Discord.

**Comment by dedwardsdale** [comment]
Sent email with prod.keys attached to you now @Thealexbarney

**Comment by Thealexbarney** [comment]
@dedwardsdale #104 fixes this. You can download it [here](https://ci.appveyor.com/project/Thealexbarney/libhac/builds/29769469/artifacts) to try it out.

**Comment by dedwardsdale** [comment]
Sorry for the late response to this, holiday season and all.
Confirmed that build is working correctly on my side too.

Thanks for the help!
