### ISSUE TITLE
ERROR: 2002-0001

### ISSUE THREAD

**Issue by max641** [Thealexbarney/LibHac#125]
Can you help me with this error. Im trying to re-encrypt with the inject file but i have some problem with a different file i use:

hactoolnet.exe -k prod.keys -t save save/0000000000000021 --replacefile /main out/0000000000000021/main
Failed to match key eticket_rsa_kek_source
Failed to match key eticket_rsa_kekek_source
Failed to match key rsa_oaep_kek_generation_source
Failed to match key rsa_private_kek_generation_source
Failed to match key ssl_rsa_kek_source_x
Failed to match key ssl_rsa_kek_source_y

ERROR: ResultFsPathNotFound (2002-0001)

Additional information:
   at LibHac.ThrowHelper.ThrowResult(Result) + 0x2c
   at LibHac.FsSystem.LocalFile..ctor(String, OpenMode) + 0x8e
   at hactoolnet.ProcessSave.Process(Context) + 0x47e
   at hactoolnet.Program.Run(String[]) + 0x271
   at hactoolnet.Program.Main(String[]) + 0x1a

**Comment by max641** [comment]
ive modified the inject file with this:
hactoolnet.exe -k prod.keys -t save save/0000000000000021 --repack out/0000000000000021/
am i right?
i seems work now but its the same thing?

**Comment by Thealexbarney** [comment]
Your first method should work for replacing a single file, but the program can't find `out/0000000000000021/main`

Are you sure the directory `out/0000000000000021/main` exists in the directory you're running the command from?
