### ISSUE TITLE
Hactoolnet cannot run as admin, getting access denied with .bat scripts.

### ISSUE THREAD

**Issue by threemor** [Thealexbarney/LibHac#136]
I'm attempting to use Hactoolnet to extract save data. When I run my extract.bat, I get an error about access denied. I am an adminstrator. I cannot run Hactoolnet as an admin, and running the extract.bat as admin does not work either. I get this error:

`D:\switch stuff\hactoolnet-0.11.2-win\ACNH>hactoolnet.exe -k prod.keys -t save sav/0000000000000018 --outdir out/0000000000000018
Failed to match key device_key_4x
Failed to match key eticket_rsa_kek_source
Failed to match key eticket_rsa_kekek_source
Failed to match key rsa_oaep_kek_generation_source
Failed to match key rsa_private_kek_generation_source
Failed to match key ssl_rsa_kek_source_x
Failed to match key ssl_rsa_kek_source_y

ERROR: Access to the path 'D:\switch stuff\hactoolnet-0.11.2-win\ACNH\sav\0000000000000018' is denied.

Additional information:
System.IO.DirectoryNotFoundException
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle) + 0x9a
   at System.IO.FileStream.CreateFileOpenHandle(FileMode, FileShare, FileOptions) + 0xa4
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare, Int32, FileOptions) + 0x14b
   at LibHac.FsSystem.LocalStorage..ctor(String, FileAccess, FileMode) + 0x51
   at hactoolnet.ProcessSave.Process(Context) + 0xa7
   at hactoolnet.Program.Run(String[]) + 0x269
   at hactoolnet.Program.Main(String[]) + 0x1a

D:\switch stuff\hactoolnet-0.11.2-win\ACNH>pause
Press any key to continue . . .`

I'm not concerned about the fails. I cannot figure out how to resolve the access denied issue. The extract.bat is running from the same folder that hactoolnet.exe is running from. It is in the same folder as the "save" folder, and it is also in the same folder as the prod.keys file.

**Comment by Thealexbarney** [comment]
Does a file with the name `D:\switch stuff\hactoolnet-0.11.2-win\ACNH\sav\0000000000000018` exist?

**Comment by threemor** [comment]
> Does a file with the name `D:\switch stuff\hactoolnet-0.11.2-win\ACNH\sav\0000000000000018` exist?

It's a folder that includes main.dat, main Header.dat, and another folder called Villager0. It does exist in the directory listed.

**Comment by Thealexbarney** [comment]
Your save data is already extracted. The command you're using is for extracting a save data file

**Comment by threemor** [comment]
Yeah, you right. I had been trying to test a couple extraction methods and didn't realize what I was using. Thanks man. Appreciate it.
