### ISSUE TITLE
NJDC  File Support

### ISSUE THREAD

**Issue by Kurainu** [Thealexbarney/LibHac#187]
Hi,
Is it possible that you add the Support for a NJDC File? Is it in the Scope for this Library?

a example File are stored in the main nca (5b688cea764e57a9595897f118a2640c.nca) from Monster Hunter Rise.
The Path inside the nca (nsw_sys\customizedDictionary\dictionary_ja.a)
Or a have attached a zip file with that file

[dictionary_ja.zip](https://github.com/Thealexbarney/LibHac/files/6338730/dictionary_ja.zip)

**Comment by Kurainu** [comment]
@Thealexbarney Any feedback on this?

**Comment by Thealexbarney** [comment]
It sounds like NJDC is a file type is specifically for that game and not used by the OS, so it wouldn't be in-scope.
