### ISSUE TITLE
How to sign a savefile?

### ISSUE THREAD

**Issue by robwilkes** [Thealexbarney/LibHac#19]
Hi,
Thanks for this great library and tool.

I'm confused with how to sign a save file.

I can extract the save contents to a directory (both save data --outdir, and all associated metadata --debugoutdir).

I've validated the save data, it is indeed the save I am interested in and is decrypted fine.

I'm having issues signing it again.

The sign argument seems to accept a single file only, not a directory.

In the source code I see only an option to extract the save file, not to create one.

I'm hoping I've just missed something really simple. Thanks in advance.

**Comment by Thealexbarney** [comment]
To clarify for others, you can use hactoolnet to resign an existing save file with the -sign option.

The tool doesn't do any save file editing at the moment.

To edit a save file, you'll need to use the library to do that.

**Comment by trulow** [comment]
@robwilkes do you mind sharing the command you used to sign the save file?

**Comment by Thealexbarney** [comment]
`hactoolnet -t save --sign filename`

**Comment by Thealexbarney** [comment]
You resign an existing save file. You can't currently create a new save file from a directory of files.

In hactoolnet v0.2.0 you can replace a file in a save file and resign it by doing `hactoolnet -t save <save_file> --replacefile <path_in_save_file> <path_to_new_file>`

For example: `hactoolnet -t save 0000000000000025 --replacefile /stuff/file.bin file.bin` will replace the file `/stuff/file.bin` in the save file with the local file `file.bin`

Note that the replacement file must be the same size as the original file at the moment.

**Comment by trulow** [comment]
Thanks, that worked. I was able to inject the file.bin into the RAW save.

One last question though, since I'm on 6.2 I cannot get all the keys without booting into CFW.

I do however have secure_boot_key, tsec_key, device_key, and all the bis_key_0x

I still get an error asking if I have all the keys. Do you think this will be an issue when loading the save?

**Comment by Thealexbarney** [comment]
If it says it couldn't sign it then it won't work. You need `save_mac_kek_source` and `save_mac_key_source`

**Comment by trulow** [comment]
Thanks, was able to grab my keys and reinject the file.bin file.

Unfortunately, after reimporting the new RAW encrypted save using HacDiskMount and launching the game, it complains that the save is corrupt.

Thanks for the help though.

**Comment by Thealexbarney** [comment]
That means you didn't sign it properly. Signatures are console-unique, so you have to use the keys from the console you're using the save with

**Comment by trulow** [comment]
@Thealexbarney 

Interesting, as I grabbed the keys using biskeydumpv7 and Lockpick from my switch that is running 6.2 via Atmosphere 8.2 so I'm sure the keys were correct. Unless the keys changed after I restored my clean NAND.

Should I also using the --sign flag?

**Comment by magpte** [comment]
> @Thealexbarney
> 
> Interesting, as I grabbed the keys using biskeydumpv7 and Lockpick from my switch that is running 6.2 via Atmosphere 8.2. Unless the keys changed after I restored my clean NAND.
> 
> Should I also using the --sign flag?
> 
> EDIT: BTW, you're awesome.
> 
> EDIT 2: I was able to figure it out.
> 
> First, I re-edited my keys.txt file and just used all the keys that Lockpick gave me.
> Secondly, I also re-edited my extract command to include the -k option when extracting the save.
> Lastly, I was able to reinject the file.bin into the save (still using the -k option), used HacDiskMount to copy the data back onto the switch, and launch the game without issues.
> 
> This is an awesome way to backup, modify, and reinject saves without having to use CFW.
> Thanks again for your help and I love your tool.

@Thealexbarney 
Also facing same issue but as I am on 7.0.0, but so far only biskeydump can dump keys, and when I am signing the file, it memtion "Required key". may I have other ways to get the key right at time?
Thanks very much with your tool, it brings great convenice other than hactool

**Comment by Thealexbarney** [comment]
No method has been released for 7.0 CFW and decrypting 7.0 firmware yet. The keys that are required are `aes_kek_generation_source`, `aes_key_generation_source`, `save_mac_kek_source`, `save_mac_key_source` and your `device_key`

**Comment by magpte** [comment]
Thanks a lot.

**Comment by MrEobo** [comment]
> 
> 
> @Thealexbarney
> 
> Interesting, as I grabbed the keys using biskeydumpv7 and Lockpick from my switch that is running 6.2 via Atmosphere 8.2. Unless the keys changed after I restored my clean NAND.
> 
> Should I also using the --sign flag?
> 
> EDIT: BTW, you're awesome.
> 
> EDIT 2: I was able to figure it out.
> 
> First, I re-edited my keys.txt file and just used all the keys that Lockpick gave me.
> Secondly, I also re-edited my extract command to include the -k option when extracting the save.
> Lastly, I was able to reinject the file.bin into the save (still using the -k option), used HacDiskMount to copy the data back onto the switch, and launch the game without issues.
> 
> This is an awesome way to backup, modify, and reinject saves without having to use CFW.
> Thanks again for your help and I love your tool.

Hey, trulow! Just wondering how exactly you managed to do this with hactoolnet?
These are my .bat files
Extract: 
```
hactoolnet.exe -k prod.keys
hactoolnet.exe -t save "sav/0000000000000019" --outdir "out/0000000000000019"
```
Inject:
```
hactoolnet.exe -k prod.keys
hactoolnet.exe -t save 0000000000000019 --replacefile /ffx_002 ffx_002
```
Sign:
```
hactoolnet.exe -k prod.keys
hactoolnet.exe -t save --sign 0000000000000019
```
I just recently thought of using a manual Sign command as I hadn't been doing so. Whenever I extract, edit, and inject the save data, I get an error on the Switch when I start up the game that says the data has been corrupted. I'm hoping the sign.bat command fixes this issue, but if not, can you lay out for us how you've done this successfully with your NAND backup? Thanks!
