### ISSUE TITLE
Rsa2048Pkcs1Verify for xci

### ISSUE THREAD

**Issue by jonnysp** [Thealexbarney/LibHac#2]
public static bool Rsa2048Pkcs1Verify(byte[] data, byte[] signature, byte[] modulus)  
        {
            bool sign = false;

            byte[] hash;
            using (SHA256 sha256 = SHA256.Create())
            {
                hash = sha256.ComputeHash(data);
            }

            using (RSACryptoServiceProvider rsa = new RSACryptoServiceProvider())
            {
                rsa.ImportParameters(new RSAParameters() { Exponent = new byte[] { 1, 0, 1 }, Modulus = modulus });

                RSAPKCS1SignatureDeformatter RSAFormatter = new RSAPKCS1SignatureDeformatter(rsa);
                RSAFormatter.SetHashAlgorithm("SHA256");

                sign = RSAFormatter.VerifySignature(hash, signature);
            }

            return sign;
        }

**Comment by jonnysp** [comment]
the modulus

Util.ToBytes("98C726B60D0A50A739210AE32FE43E2E5BA28675AA5CEE34F1A33A7EBD904EF78DFA17AA6BC6366D4C9A6D572F80A2BC384DDA99A1D8C3E2997936719020259D4D11B82E636B5AFA1E9C04D1C5F09CB10FB8C17BBFE8B0D22B4701226B23C9D0BCEB756E417D4C26A47321B4F014E5D98DB364EEA8FA841BB8B87C886BEFCC9704049A672FDFEC0DB25FB5B2BDB54BDE0E88A3BAD1B4E09181A784EB77858BEFA5E327B2F2822B29F1752DCECCAE9B8DED5CF18EDB9AD7AF421452CDE3C5DDCE081217D07F1AAA1F7DE09354C8BC738ACBAD6E93E219726BD345F8733D2B6A55D23A8BB08A42E33DF19223422EBACC9C9AC1DD62869C2EE12D6F626751080ECF");

**Comment by Thealexbarney** [comment]
Added in 1f62706
