### ISSUE TITLE
Specified padding mode is not valid for this algorithm.

### ISSUE THREAD

**Issue by garoxas** [Thealexbarney/LibHac#22]
Hi,
I'm developing an app for macOS using LibHac, and getting crashes during loading NCA

Here's the stacktrace
```
LibHac.Crypto.Rsa2048PssVerify(byte[] data, byte[] signature, byte[] modulus) in C:/LibHac/Crypto.cs:167
LibHac.NcaHeader..ctor(System.IO.BinaryReader reader, LibHac.Keyset keyset) in C:/LibHac/NcaStructs.cs:42
LibHac.Nca.DecryptHeader() in C:/LibHac/Nca.cs:308
LibHac.Nca..ctor(LibHac.Keyset keyset, LibHac.IO.SubStorage storage, bool leaveOpen) in C:/LibHac/Nca.cs:37
```

So when calling `rsa.VerifyData(data, signature, HashAlgorithmName.SHA256, RSASignaturePadding.Pss)` in Rsa2048PssVerify (Crypto.cs:157), it always crashes with `System.Security.Cryptography.CryptographicException: Specified padding mode is not valid for this algorithm.` exception

Based on what I read here https://github.com/dotnet/corefx/blob/master/Documentation/architecture/cross-platform-cryptography.md#rsa, apparently PSS padding is not supported when not using RSACng (which is only available on Windows)
Is there any workaround for that?

PS. I'm building from the source with USE_RSA_CNG disabled
If I enable it, then I'll get System.NotImplementedException instead. I guess RSACng implementation in Mono just throw that exception by default https://github.com/mono/mono/blob/master/mcs/class/referencesource/System.Core/System/Security/Cryptography/RsaCng.cs

**Comment by Thealexbarney** [comment]
It works properly on .NET Core. I'm guessing you need Mono support?

**Comment by garoxas** [comment]
Yes. The PR I made works on macOS but as you said it's including an entire library just for one RSA-PSS verification function

**Comment by Thealexbarney** [comment]
I've written the code to do the verification without the framework's crypto APIs. It should be committed soon
