### ISSUE TITLE
VerifyHeaderSignature always return invalid

### ISSUE THREAD

**Issue by D3fau4** [Thealexbarney/LibHac#228]
since 0.14 whenever I do a "VerifyHeaderSignature" it returns that the header is invalid.

```cs
                            if (ncas[i].VerifyHeaderSignature() == LibHac.Validity.Valid)
                            {
                                FileSystemClient fs = hos.horizon.Fs;
                                fs.Register("exefs".ToU8Span(), OpenFileSystemByType(NcaSectionType.Code, ncas[i]));
                                fs.Register("romfs".ToU8Span(), OpenFileSystemByType(NcaSectionType.Data, ncas[i]));
                            }
```

this also happen in hactoolnet returning always: `Fixed-Key Signature (FAIL):`

**Comment by Thealexbarney** [comment]
Are you sure the signature is valid? I'm not having any issues with hactoolnet saying the signature is invalid when it's actually valid. What NCAs are you seeing the issue with?

**Comment by D3fau4** [comment]
Currently with ncas extracted from a dump of my cartridges, and original copies from the eshop. in general I get in any nca a error.
I may have implemented the system wrong but in previous versions it worked perfectly:
[https://github.com/TraduSquare/Mara/blob/0b0879ae54e373708f6729de6acf70c1a06399a8/Mara.Lib/Platforms/Switch/NCA.cs#L34](url)
this is a tool I'm working on to apply patches to games (specially translation patchs) and I have a system to detect that the copy is "legal" and warn the user to please buy the game. but since the 0.14.0 i always get invalid signature from that.

**Comment by Thealexbarney** [comment]
Is there a reason you're not pulling in libhac as a PackageReference from NuGet?

**Comment by D3fau4** [comment]
I used the DLL to get the latest changes from the repo, but the last commit already referenced from nuget.

**Comment by Thealexbarney** [comment]
> this also happen in hactoolnet returning always: `Fixed-Key Signature (FAIL):`

Are you using the builds of hactoolnet from the GitHub releases?

**Comment by D3fau4** [comment]
Not actually.

**Comment by Thealexbarney** [comment]
If you're building it yourself, you either need to use the build script or run `build.cmd codegen` first if you're building it in Visual Studio
