### ISSUE TITLE
Application.DisplayVersion prints Array16 type

### ISSUE THREAD

**Issue by Tiddlywinkss** [Thealexbarney/LibHac#233]
[In a Jan 2 update to ApplicationControlProperty.cs](https://github.com/Thealexbarney/LibHac/commit/b0e679d00043d347b0f560c78b8de4210255691b#diff-f8d922ce808e75fdbff15b6fcbe2a8ed503b5bc4259a7a77a622067f0da7308b), DisplayVersion was changed from a U8SpanMutable to Array16\<byte\>. U8SpanMutable had a ToString override, Array16\<byte\> does not. So Application.DisplayVersion ([assigned from ApplicationControlProperty.DisplayVersion](https://github.com/Thealexbarney/LibHac/blob/0846b86249c88230ad97781c54664df4bddc5862/src/LibHac/Tools/Fs/SwitchFs.cs#L409)) just holds the type name (as in `typeof( LibHac.Common.FixedArrays.Array16<byte> ).ToString()`).

**Comment by Thealexbarney** [comment]
Thanks, I thought I got all of those instances, but I guess I missed some
