### ISSUE TITLE
[Request] Add nsz,ncz and xcz support

### ISSUE THREAD

**Issue by mrissaoussama** [Thealexbarney/LibHac#292]
Hello, can you add support for ncz and xcz file formats? at least for reading info. details about the formats are here https://github.com/nicoboss/nsz#file-format-details
attempting to open those causes a nre in FileSystemExtensions
![image](https://github.com/Thealexbarney/LibHac/assets/29640959/83f0fbd3-ee49-4ccf-9099-3bd7d56cb10c)

**Comment by Thealexbarney** [comment]
Adding support for these formats is not planned

**Comment by Kiriox94** [comment]
> Adding support for these formats is not planned

If I make a pr, could you accept it?
