### ISSUE TITLE
Incorrect NCA file name

### ISSUE THREAD

**Issue by ivaano** [Thealexbarney/LibHac#294]
There is a regression bug in version 19, not happening on version 18. The Control NCA is returned as null because it doesn't match the `"*.nca"` pattern. This is the output of version 19.

```
 .\hactoolnet.exe -t pfs0 "N:\test\nca_fail.nsp" --listncas

PFS0:
Magic:                              PFS0
Number of files:                    7
Files:                              pfs0:/01007ef00011e0000000000000000000.cert
                                    pfs0:/01007ef00011e0000000000000000000.tik
                                    pfs0:/861707001401bbce36c7e421efac76d4.nca
                                    pfs0:/4e87c750004425979032be0f6c003f7a.nca
                                    pfs0:/1696391d880b1f08e8145e1a15c8a969.cnmt.nca
                                    pfs0:/1696391d880b1f08e8145e1a15c8a969.cnmt.xml
                                    pfs0:/2560c86ce554b762d54bc94132c9f491.nc

NCA ID                           Type    Title ID
1696391d880b1f08e8145e1a15c8a969 Meta    01007EF00011E000
4e87c750004425979032be0f6c003f7a Manual  01007EF00011E000
861707001401bbce36c7e421efac76d4 Program 01007EF00011E000
```
File `pfs0:/2560c86ce554b762d54bc94132c9f491.nc` should be `pfs0:/2560c86ce554b762d54bc94132c9f491.nca`

This is with version 18 and it returns the correct name

```
.\18\hactoolnet.exe -t pfs0 "N:\test\nca_fail.nsp" --listncas
Failed to match key device_key_4x
Failed to match key eticket_rsa_kek_source
Failed to match key eticket_rsa_kekek_source
Failed to match key save_mac_key
Failed to match key ssl_rsa_kek_source
Failed to match key ssl_rsa_kekek_source
Failed to match key ssl_rsa_key

PFS0:
Magic:                              PFS0
Number of files:                    7
Files:                              pfs0:/01007ef00011e0000000000000000000.cert
                                    pfs0:/01007ef00011e0000000000000000000.tik
                                    pfs0:/861707001401bbce36c7e421efac76d4.nca
                                    pfs0:/4e87c750004425979032be0f6c003f7a.nca
                                    pfs0:/1696391d880b1f08e8145e1a15c8a969.cnmt.nca
                                    pfs0:/1696391d880b1f08e8145e1a15c8a969.cnmt.xml
                                    pfs0:/2560c86ce554b762d54bc94132c9f491.nca

NCA ID                           Type    Title ID
1696391d880b1f08e8145e1a15c8a969 Meta    01007EF00011E000
2560c86ce554b762d54bc94132c9f491 Control 01007EF00011E000
4e87c750004425979032be0f6c003f7a Manual  01007EF00011E000
861707001401bbce36c7e421efac76d4 Program 01007EF00011E000
```

I did a quick analysis and the [`entryName`](https://github.com/Thealexbarney/LibHac/blob/f28e7a7dbb72bfcca4872bfee9b69429619def14/src/LibHac/FsSystem/PartitionFileSystem.cs#L372) from the metadata is returning the right name, but when it is passed to [`StringUtils.Strlcpy`](https://github.com/Thealexbarney/LibHac/blob/f28e7a7dbb72bfcca4872bfee9b69429619def14/src/LibHac/Util/StringUtils.cs#L41) that's when the last char is chopped.

This are the array values of source and dest vars after it finished that iteration, and we can see that the value 35 is set to 0 because it doesn't perform the last iterantion `for (int i = 0; iDest < dest.Length && i < source.Length && source[i] != 0; i++, iDest++)`

```
source						dest
[0] = {byte} 50				[0] = {byte} 50
[1] = {byte} 53				[1] = {byte} 53
[2] = {byte} 54				[2] = {byte} 54
[3] = {byte} 48				[3] = {byte} 48
[4] = {byte} 99				[4] = {byte} 99
[5] = {byte} 56				[5] = {byte} 56
[6] = {byte} 54				[6] = {byte} 54
[7] = {byte} 99				[7] = {byte} 99
[8] = {byte} 101			[8] = {byte} 101
[9] = {byte} 53				[9] = {byte} 53
[10] = {byte} 53			[10] = {byte} 53
[11] = {byte} 52			[11] = {byte} 52
[12] = {byte} 98			[12] = {byte} 98
[13] = {byte} 55			[13] = {byte} 55
[14] = {byte} 54			[14] = {byte} 54
[15] = {byte} 50			[15] = {byte} 50
[16] = {byte} 100			[16] = {byte} 100
[17] = {byte} 53			[17] = {byte} 53
[18] = {byte} 52			[18] = {byte} 52
[19] = {byte} 98			[19] = {byte} 98
[20] = {byte} 99			[20] = {byte} 99
[21] = {byte} 57			[21] = {byte} 57
[22] = {byte} 52			[22] = {byte} 52
[23] = {byte} 49			[23] = {byte} 49
[24] = {byte} 51			[24] = {byte} 51
[25] = {byte} 50			[25] = {byte} 50
[26] = {byte} 99			[26] = {byte} 99
[27] = {byte} 57			[27] = {byte} 57
[28] = {byte} 102			[28] = {byte} 102
[29] = {byte} 52			[29] = {byte} 52
[30] = {byte} 57			[30] = {byte} 57
[31] = {byte} 49			[31] = {byte} 49
[32] = {byte} 46			[32] = {byte} 46
[33] = {byte} 110			[33] = {byte} 110
[34] = {byte} 99			[34] = {byte} 99
[35] = {byte} 97			[35] = {byte} 0
						[36] = {byte} 116
						[37] = {byte} 46
						[38] = {byte} 120
						[39] = {byte} 109
						[40] = {byte} 108
```

I don't know why it happens on this file, other ncas work as expected, a simple fix I did is to make it less or equal, it works fine but I don't know if it might impact something else because the StringUtils file hasn't been changed since last year, so this bug was probably introduced somewhere else.

`for (int i = 0; iDest <= dest.Length && i < source.Length && source[i] != 0; i++, iDest++)`

I can submit a PR if necessary.

regards

**Comment by Thealexbarney** [comment]
The issue stems from our strlcpy taking in Spans instead of pointers, so there are 3 different lengths to take into account because we treat the end of a span as an implicit null byte. Apparently I didn't consider this when adding the function, so it ended up truncating the data here by one byte so it could place the null terminator.

AFAICT, this specific issue should only happen when the name table in the pfs is completely full without any room for a null terminator at the end.

I'll go ahead and redesign how the function handles this

**Comment by Thealexbarney** [comment]
Can you confirm that #303 fixes the issue? You can get a build here https://ci.appveyor.com/project/Thealexbarney/libhac/builds/49795956/artifacts
