### ISSUE TITLE
Terra cartridges do not pass "Partition Header Hash" verification.

### ISSUE THREAD

**Issue by Whovian9369** [Thealexbarney/LibHac#305]
Terra cartridges appear to differ from cartridges for non-Terra systems as Partition Header Hash verification fails outright.

**Comment by DarkMatterCore** [comment]
https://github.com/DarkMatterCore/nxdumptool/commit/503ce4c1a74e9b0cc45792961254f175e5e71976 fixes the same exact issue within nxdumptool.
