### ISSUE TITLE
RomFs broken

### ISSUE THREAD

**Issue by jonnysp** [Thealexbarney/LibHac#32]
i try to extrakt the Romfs from XCI with hacktoolnet. i become an error directory not found.
the xci is 0100F17004156000  Retro City Rampage DX.
the command  "hactoolnet.exe -t xci -h -k prod.keys --romfsdir test test.xci"
it worked before you made the last changes to the romfs
can you check this?

**Comment by Thealexbarney** [comment]
Can you run a few commands?

Get the romfs from the xci
`hactoolnet.exe -t xci --romfs romfs test.xci`

Try to extract the romfs
`hactoolnet.exe -t romfs --romfsdir romfs_out romfs`

If that doesn't work, send me the output of the above command and the list of files in the romfs
`hactoolnet.exe -t romfs --listromfs romfs`

**Comment by jonnysp** [comment]
The same 

hactoolnet.exe -t romfs --listromfs romfs

ERROR: Es wurde versucht, auf einen Pfad zuzugreifen, der nicht auf dem Datenträger ist.

Additional information:
System.IO.DirectoryNotFoundException
   bei LibHac.IO.RomFs.RomFsFileSystem.OpenDirectory(String path, OpenDirectoryMode mode)
   bei LibHac.IO.FileSystemExtensions.EnumerateEntries(IFileSystem fileSystem)
   bei hactoolnet.ProcessRomfs.Process(Context ctx, RomFsFileSystem romfs)
   bei hactoolnet.ProcessRomfs.Process(Context ctx)
   bei hactoolnet.Program.RunTask(Context ctx)
   bei hactoolnet.Program.Run(String[] args)
   bei hactoolnet.Program.Main(String[] args)

![grafik](https://user-images.githubusercontent.com/1651241/52837737-3e7a5680-30f0-11e9-84d5-084e6230f1de.png)

**Comment by jonnysp** [comment]
very nice thanks

**Comment by Thealexbarney** [comment]
Thanks for the report. I might not have caught that otherwise
