### ISSUE TITLE
exception thrown when repeatedly reading without checking if at end of file of any nand partition file.

### ISSUE THREAD

**Issue by CaitSith2** [Thealexbarney/libhac#5]
It has been noted that the Fat Library included throws an exception, if end of file has been reached AND you attempt to do another buffer read,  instead of normal c# behavior of returning 0 indicating that nothing has been read.   I will fix my code to not do that anymore, but it still has a potential to be an issue for anyone else using the library assuming they can just charge through with big reads, without checking how close to the end the read is.

**Comment by CaitSith2** [comment]
Seems to by a DiskUtils behaviour.

**Comment by Thealexbarney** [comment]
Fixed by #7
