### ISSUE TITLE
attempting to open "save\80000000000000e1" on sysnand throws a name too long exception.

### ISSUE THREAD

**Issue by CaitSith2** [Thealexbarney/libhac#6]
Seems File.Exists happily returns the existent of the long filename of save\80000000000000e1,  but attempting to open it causes the name too long exception.  (same for any other save file).

**Comment by Thealexbarney** [comment]
I've been using it without issue here https://github.com/Thealexbarney/libhac/blob/master/NandReader/Program.cs#L90

DiscUtils master branch doesn't support long FAT names, but there's a PR I pulled in to support them

**Comment by CaitSith2** [comment]
Traced the exception back to https://github.com/Thealexbarney/libhac/blob/master/libhac.Nand/DiscUtils.Fat/FileName.cs#L141 (The longfilename parameter is set to false)

**Comment by CaitSith2** [comment]
Seems to have been an issue actually of me attempting to open "save\80000000000000e1" instead of "save\80000000000000E1".  Seems that unfortunately, case matters when it comes to long filenames, or at the very least there are cases where the string compare is failing due to mismatched case.

**Comment by CaitSith2** [comment]
I addressed the issue in Pull request #7.

**Comment by Thealexbarney** [comment]
Fixed in #7
