### ISSUE TITLE
Compatibility to big endian systems?

### ISSUE THREAD

**Issue by TechInterMezzo** [Thealexbarney/LibHac#75]
This is more a question than a bug report as I haven't tested that assumption yet. There are stilll things I want to learn about cross platform programming.

I saw the use of [Unsafe.As](https://github.com/Thealexbarney/LibHac/blob/master/src/LibHac/Fs/NcaUtils/NcaHeader.cs#L28) in the code and I asked myself if this code could run on systems with big endian instead of little endian like windows. To my understand it just reinterprets the binary pointer as a struct and thus relies on the endianness of the system?

(Btw. great library and clean architecture.)

**Comment by Thealexbarney** [comment]
Unfortunately big endian systems aren't supported for performance reasons. There are parts of the library that would be many times slower and use more memory if data structures had to be loaded differently based on the system's endianness.

I didn't think anybody would run the library on a big-endian system. What CPU are you using?

**Comment by TechInterMezzo** [comment]
Thank you for the clarification. That's enough for me.

**Comment by Thealexbarney** [comment]
I'm still curious what system you're using that's big endian. Or was this a theoretical question?

And your understanding of Unsafe.As is correct.

**Comment by TechInterMezzo** [comment]
It was just theoretical.
