### ISSUE TITLE
Yaz0 and Sarc contentfiles

### ISSUE THREAD

**Issue by jonnysp** [Thealexbarney/LibHac#78]
hi alex,

i have ported Yaz0 and Sarc (both readonly) contentfiles for your libhac library. 
should i create a brunch?

jonny

**Comment by Thealexbarney** [comment]
Does Horizon use these file types?

**Comment by jonnysp** [comment]
Yes I think. In the firmware files of the Xci are szs files, there are yaz0 files these can contain sarc files. These include Translation and Styles for the GUI. Some theme creators use this.

**Comment by Thealexbarney** [comment]
I'm not sure that those formats would be part of the library's scope. It sounds like that they're used by an application rather than sysmodules.

**Comment by jonnysp** [comment]
i think the Application is the Firmware itself. N uses this comression algo for many application and is a component of the firmware.

**Comment by jonnysp** [comment]
at example the netconnect module used these as resources
![grafik](https://user-images.githubusercontent.com/1651241/66370246-c541b380-e99f-11e9-9e41-3fbc0e7bb070.png)
