### ISSUE TITLE
When signing SAVE file 800000000000120 get CMAC Signature (FAIL)

### ISSUE THREAD

**Issue by RetroGamer74** [Thealexbarney/LibHac#82]
Hi, I'd like to point an issue with hactoolnet. Trying to run the command:
hactoolnet -t save -k prod.keys NX-X.Y.Z\SYSTEM\save\8000000000120 I get a result of failure that can be workarounded, repeating the command several times. Some times I get a GOOD result after 3 runs, others 8 runs .... I guess, maybe there is a memory issue when loading the keys. The keys file is growing and maybe memory reservation for reading the keys file is wrong.

I'm using prod.keys generated by lock pick RCM against firmware 9.0.1.

If you need further info don't hesitate to answer to me.

Thank you.

**Comment by Thealexbarney** [comment]
To sign the save you need to either specify `--sign` or do an operation that modifies the save file.

Running that command shouldn't be signing the save at all. What version of hactoolnet are you running?

**Comment by Thealexbarney** [comment]
Closing if there's no other info
