### ISSUE TITLE
Error 2002-0001 on save repack

### ISSUE THREAD

**Issue by SADXfan01** [Thealexbarney/LibHac#86]
I've been trying to repack a BotW save, and don't really know what's going on here. Is something wrong with the syntax?

hactoolnet_native.exe -k (key file in same folder) -t save (save location) --repack (Folder with unpacked save)
![Annotation 2019-10-16 183000](https://user-images.githubusercontent.com/8353208/66963926-fdea2880-f042-11e9-95d8-9d225ed6443c.png)

**Comment by Thealexbarney** [comment]
PR #87 should fix this issue. Can you test it?

You can grab a build from [AppVeyor](https://ci.appveyor.com/project/Thealexbarney/libhac/builds/28165093/artifacts)

**Comment by SADXfan01** [comment]
Works like a charm, thanks chief.
